### ISSUE TITLE
[Баг] Необработанное исключение 

### ISSUE THREAD

**Issue by Sadzurami** [SmallTailTeam/BotLooter#75]
```txt
System.NullReferenceException: Object reference not set to an instance of an object.
   at BotLooter.Steam.Contracts.TradeOfferUrl.ToPartner() in /Users/admin/desktop/BotLooter/BotLooter/Steam/Contracts/TradeOfferUrl.cs:line 29
   at BotLooter.Steam.Contracts.TradeOfferUrl.get_Partner() in /Users/admin/desktop/BotLooter/BotLooter/Steam/Contracts/TradeOfferUrl.cs:line 8
   at BotLooter.Steam.SteamWeb.SendTradeOffer(TradeOfferUrl tradeOfferUrl, JsonTradeOffer jsonTradeOffer) in /Users/admin/desktop/BotLooter/BotLooter/Steam/SteamWeb.cs:line 128
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at BotLooter.Looting.LootClient.SendTradeOffer(TradeOfferUrl tradeOfferUrl, JsonTradeOffer tradeOffer) in /Users/admin/desktop/BotLooter/BotLooter/Looting/LootClient.cs:line 222
   at BotLooter.Looting.LootClient.TryLoot(TradeOfferUrl tradeOfferUrl, Configuration configuration) in /Users/admin/desktop/BotLooter/BotLooter/Looting/LootClient.cs:line 88
   at BotLooter.Looting.Looter.<>c__DisplayClass5_0.<<Loot>b__0>d.MoveNext() in /Users/admin/desktop/BotLooter/BotLooter/Looting/Looter.cs:line 39
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at BotLooter.Looting.Looter.Loot(List`1 lootClients, TradeOfferUrl tradeOfferUrl, Configuration config) in /Users/admin/desktop/BotLooter/BotLooter/Looting/Looter.cs:line 29
   at Program.<Main>$(String[] args) in /Users/admin/desktop/BotLooter/BotLooter/Program.cs:line 69
   at Program.<Main>(String[] args)
dUnhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at BotLooter.Steam.Contracts.TradeOfferUrl.ToPartner() in /Users/admin/desktop/BotLooter/BotLooter/Steam/Contracts/TradeOfferUrl.cs:line 29
   at BotLooter.Steam.Contracts.TradeOfferUrl.get_Partner() in /Users/admin/desktop/BotLooter/BotLooter/Steam/Contracts/TradeOfferUrl.cs:line 8
   at BotLooter.Steam.SteamWeb.SendTradeOffer(TradeOfferUrl tradeOfferUrl, JsonTradeOffer jsonTradeOffer) in /Users/admin/desktop/BotLooter/BotLooter/Steam/SteamWeb.cs:line 128
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at BotLooter.Looting.LootClient.SendTradeOffer(TradeOfferUrl tradeOfferUrl, JsonTradeOffer tradeOffer) in /Users/admin/desktop/BotLooter/BotLooter/Looting/LootClient.cs:line 222
   at BotLooter.Looting.LootClient.TryLoot(TradeOfferUrl tradeOfferUrl, Configuration configuration) in /Users/admin/desktop/BotLooter/BotLooter/Looting/LootClient.cs:line 88
   at BotLooter.Looting.Looter.<>c__DisplayClass5_0.<<Loot>b__0>d.MoveNext() in /Users/admin/desktop/BotLooter/BotLooter/Looting/Looter.cs:line 39
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
--- End of stack trace from previous location ---
   at BotLooter.Looting.Looter.Loot(List`1 lootClients, TradeOfferUrl tradeOfferUrl, Configuration config) in /Users/admin/desktop/BotLooter/BotLooter/Looting/Looter.cs:line 29
   at Program.<Main>$(String[] args) in /Users/admin/desktop/BotLooter/BotLooter/Program.cs:line 69
   at Program.<Main>(String[] args)
```

**Comment by Lyrapuff** [comment]
ea47d2be16c0995a4b8c482016354f500b8f0283 возможно исправляет
